[package]
name = "img2a"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.7"
terminal_size = "0.3.0"
rand = "0.8.5"
colored = "2.0.4"

